## **Lab 3 - Find-S and Candidate Elimination Algorithms**
### **Name: Shubhi Kumari**
### **Batch: C-C3**
### **Roll no: 34**
### **ML Lab**

In [56]:
import pandas as pd
import numpy as np

In [57]:
df=pd.read_csv("enjoy.csv")
print(df)

      Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0   Sunny    Warm   Normal  Strong  Warm     Same        Yes
1   Sunny    Warm     High  Strong  Warm     Same        Yes
2   Rainy    Cold     High  Strong  Warm   Change         No
3   Sunny    Warm     High  Strong  Cool   Change        Yes
4   Sunny    Cold   Normal    Weak  Warm     Same         No
5  Cloudy    Warm   Normal    Weak  Warm     Same         No
6   Sunny    Warm   Normal    Weak  Cool     Same        Yes
7   Rainy    Warm     High    Weak  Cool   Change         No
8   Sunny    Warm   Normal  Strong  Cool     Same        Yes
9   Sunny    Warm     High    Weak  Warm     Same        Yes

In [58]:
df.head()

     Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes
4  Sunny    Cold   Normal    Weak  Warm     Same         No

In [59]:
df.tail()

      Sky AirTemp Humidity    Wind Water Forecast EnjoySport
5  Cloudy    Warm   Normal    Weak  Warm     Same         No
6   Sunny    Warm   Normal    Weak  Cool     Same        Yes
7   Rainy    Warm     High    Weak  Cool   Change         No
8   Sunny    Warm   Normal  Strong  Cool     Same        Yes
9   Sunny    Warm     High    Weak  Warm     Same        Yes

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sky         10 non-null     object
 1   AirTemp     10 non-null     object
 2   Humidity    10 non-null     object
 3   Wind        10 non-null     object
 4   Water       10 non-null     object
 5   Forecast    10 non-null     object
 6   EnjoySport  10 non-null     object
dtypes: object(7)
memory usage: 692.0+ bytes

In [61]:
df.describe()

          Sky AirTemp Humidity    Wind Water Forecast EnjoySport
count      10      10       10      10    10       10         10
unique      3       2        2       2     2        2          2
top     Sunny    Warm   Normal  Strong  Warm     Same        Yes
freq        7       8        5       5     6        7          6

In [62]:
df.shape

(10, 7)

In [63]:
df.columns

Index(['Sky', 'AirTemp', 'Humidity', 'Wind', 'Water', 'Forecast',
       'EnjoySport'],
      dtype='object')

## **Find-S Algorithm**

**The Find-S algorithm finds the most specific hypothesis that is consistent with all positive training examples. It starts with the most specific hypothesis and generalizes it whenever a positive example contains a different attribute value. Negative examples are ignored by the Find-S algorithm.**

In [64]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [65]:
def find_s(X,y):
    hypothesis=None
    print("Initial Hypothesis: ",hypothesis)
    for i in range(len(X)):
        if y[i]=="Yes":
            if hypothesis is None:
                hypothesis=X[i].copy()
            else:
                for j in range(len(hypothesis)):
                    if hypothesis[j]!=X[i][j]:
                        hypothesis[j]="?"
        print(f"\nAfter Training Example {i+1}")
        print(hypothesis)
    return hypothesis

In [66]:
final_hypothesis=find_s(X,y)
print("\nFinal Hypothesis")
print(final_hypothesis)

Initial Hypothesis:  None

After Training Example 1
['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']

After Training Example 2
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After Training Example 3
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After Training Example 4
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 5
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 6
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 7
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 8
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 9
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 10
['Sunny' 'Warm' '?' '?' '?' '?']

Final Hypothesis
['Sunny' 'Warm' '?' '?' '?' '?']


## **Candidate Elimination Algorithm**

**The Candidate Elimination algorithm is a concept learning algorithm used to find all hypotheses that are consistent with the given training examples.**

In [67]:
# Function to implement Candidate Elimination Algorithm
def candidate_elimination(concepts, target):

    # Initialize Specific hypothesis with the first positive training example
    first_pos_index = target.index("Yes")
    specific = concepts[first_pos_index].copy()

    # Initialize General hypothesis with '?' for every attribute
    general = [["?" for _ in range(len(specific))]]

    # Display initial hypotheses
    print("\nInitial S:", specific)
    print("Initial G:", general)

    # Process each training example
    for i, h in enumerate(concepts):

        # ------------------------------------------------
        # Positive Training Example
        # ------------------------------------------------
        if target[i] == "Yes":

            # Generalize the Specific hypothesis
            for x in range(len(specific)):

                # If the attribute value is different,
                # replace it with '?'
                if h[x] != specific[x]:
                    specific[x] = "?"

            # Remove general hypotheses that do not
            # cover the positive example
            general = [
                g
                for g in general
                if all(
                    g[j] == "?" or g[j] == h[j] for j in range(len(specific))
                )
            ]

        # ------------------------------------------------
        # Negative Training Example
        # ------------------------------------------------
        else:

            new_general = []

            # Specialize the General hypotheses
            for g in general:

                # Check whether the hypothesis covers
                # the negative example
                covers_negative = all(
                    g[j] == "?" or g[j] == h[j] for j in range(len(specific))
                )

                # If it covers the negative example,
                # specialize it
                if covers_negative:

                    for x in range(len(specific)):

                        # Only specialize '?' positions
                        if g[x] == "?":

                            # Use the Specific boundary value
                            if specific[x] != "?" and specific[x] != h[x]:
                                # Create a copy of the hypothesis
                                hypothesis = g.copy()
                                hypothesis[x] = specific[x]

                                # Add if it is not already present
                                if hypothesis not in new_general:
                                    new_general.append(hypothesis)

                else:
                    # Keep hypotheses that do not cover
                    # the negative example
                    if g not in new_general:
                        new_general.append(g)

            # Update General boundary
            general = new_general

        # Remove duplicate hypotheses
        unique_general = []

        for g in general:
            if g not in unique_general:
                unique_general.append(g)

        general = unique_general

        # Display the boundaries after each example
        print(f"\nExample {i + 1} ({'Positive' if target[i] == 'Yes' else 'Negative'}):")
        print("Instance:", h)
        print("S =", specific)
        print("G =", general)

    # Return final boundaries
    return specific, general


# ------------------------------------------------
# Load CSV and Run Algorithm
# ------------------------------------------------
df = pd.read_csv("enjoy.csv")

# Extract features (concepts) and target labels
X = df.iloc[:, :-1].values.tolist()
y = df.iloc[:, -1].values.tolist()

# Run Candidate Elimination
S, G = candidate_elimination(X, y)

# Display final boundaries
print("\n" + "=" * 40)
print("Final Specific Boundary:")
print(S)

print("\nFinal General Boundary:")
for g in G:
    print(g)
print("=" * 40)

Initial S: ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']
Initial G: [['?', '?', '?', '?', '?', '?']]

Example 1 (Positive):
Instance: ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']
S = ['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 2 (Positive):
Instance: ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same']
S = ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']
G = [['?', '?', '?', '?', '?', '?']]

Example 3 (Negative):
Instance: ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change']
S = ['Sunny', 'Warm', '?', 'Strong', 'Warm', 'Same']
G = [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]

Example 4 (Positive):
Instance: ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change']
S = ['Sunny', 'Warm', '?', 'Strong', '?', '?']
G = [['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?']]

Example 5 (Negative):
Instance: ['Sunny', 'Cold', 'Normal', 'Weak', 'Warm', 'Same']
S = ['Sunny', 'Warm', '?', 'Strong', '?', '?']
G = [['Sunny', 'Warm', '?', '?', '?', '?'], ['Sunny', '?', '?', 'Strong', '?', '?'], ['?', 'Warm', '?', '?', '?', '?']]

Example 6 (Negative):
Instance: ['Cloudy', 'Warm', 'Normal', 'Weak', 'Warm', 'Same']
S = ['Sunny', 'Warm', '?', 'Strong', '?', '?']
G = [['Sunny', 'Warm', '?', '?', '?', '?'], ['Sunny', '?', '?', 'Strong', '?', '?'], ['?', 'Warm', '?', 'Strong', '?', '?']]

Example 7 (Positive):
Instance: ['Sunny', 'Warm', 'Normal', 'Weak', 'Cool', 'Same']
S = ['Sunny', 'Warm', '?', '?', '?', '?']
G = [['Sunny', 'Warm', '?', '?', '?', '?']]

Example 8 (Negative):
Instance: ['Rainy', 'Warm', 'High', 'Weak', 'Cool', 'Change']
S = ['Sunny', 'Warm', '?', '?', '?', '?']
G = [['Sunny', 'Warm', '?', '?', '?', '?']]

Example 9 (Positive):
Instance: ['Sunny', 'Warm', 'Normal', 'Strong', 'Cool', 'Same']
S = ['Sunny', 'Warm', '?', '?', '?', '?']
G = [['Sunny', 'Warm', '?', '?', '?', '?']]

Example 10 (Positive):
Instance: ['Sunny', 'Warm', 'High', 'Weak', 'Warm', 'Same']
S = ['Sunny', 'Warm', '?', '?', '?', '?']
G = [['Sunny', 'Warm', '?', '?', '?', '?']]

========================================
Final Specific Boundary:
['Sunny', 'Warm', '?', '?', '?', '?']

Final General Boundary:
['Sunny', 'Warm', '?', '?', '?', '?']
========================================

In [68]:
# Compare the results of Find-S and Candidate Elimination

print("========== COMPARISON OF HYPOTHESES ==========")

print("\nFind-S Final Hypothesis:")
print(final_hypothesis)

print("\nCandidate Elimination Specific Boundary:")
print(specific_boundary)

print("\nCandidate Elimination General Boundary:")
for hypothesis in general_boundary:
    print(hypothesis)

========== COMPARISON OF HYPOTHESES ==========

Find-S Final Hypothesis:
['Sunny' 'Warm' '?' '?' '?' '?']

Candidate Elimination Specific Boundary:
['Sunny', 'Warm', '?', '?', '?', '?']

Candidate Elimination General Boundary:
['?', '?', '?', '?', '?', '?']
['Sunny', 'Warm', '?', '?', '?', '?']
['Sunny', '?', '?', '?', '?', '?']
['?', 'Warm', '?', '?', '?', '?']